source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'WBNetworkRequest_Example' do
  pod 'WBNetworkRequest', :path => '../'
  pod 'WBExtendTools','~>1.0.5'
pod ''
 
end
